# ============================
# MAIN PIPELINE (GitHub Actions)
# ============================
name: Main Pipeline

on:
  workflow_dispatch: # rÄ™czne uruchomienie

# ============================
# JOBY
# ============================
jobs:
  build:
    name: ðŸ”§ Build stage
    runs-on: ubuntu-latest

    steps:
      - name: ðŸ“¥ Checkout code
        uses: actions/checkout@v4

      - name: ðŸ Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: âš™ï¸ Install dependencies
        run: |
          pip install --no-cache-dir -r requirements.txt
          pip install pytest

      - name: ðŸ³ Build Docker image
        run: docker build -t webapp-hello:0.1 .

  tests:
    name: ðŸ§ª Run tests
    runs-on: ubuntu-latest
    needs: build
      
    steps:
      - name: ðŸ“¥ Checkout code
        uses: actions/checkout@v4

      - name: ðŸ§­ Set PYTHONPATH
        run: echo "PYTHONPATH=$PWD" >> $GITHUB_ENV

      - name: ðŸ§ª pytest
        run: pytest -v
    